<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Activecontent
 * @version    1.1.3
 * @copyright  Copyright (c) 2011-2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<div class="ac-sort">
    <input type="hidden" class="link_id" value="<?php echo $this->getId() ?>" />
    <div class="value" id="value_<?php echo $this->getId() ?>"><?php echo $this->getValue()?></div>
    <div class="loader" id="loader_<?php echo $this->getId() ?>"><img src="<?php echo $this->getSkinUrl('mp_activecontent/images/small-ajax-loader.gif'); ?>"/></div>
    <div class="value-edit" id="value_edit_<?php echo $this->getId() ?>">
        <input type="text" class="input-text" id="value_input_<?php echo $this->getId() ?>" name="order_value" value="<?php echo $this->getValue()?>" />
        <div class="btn-save" id="btn_save_<?php echo $this->getId() ?>"><img src="<?php echo $this->getSkinUrl('mp_activecontent/images/button_save.gif'); ?>" /></div>
    </div>
</div>
<script type="text/javascript">
    sortorder.setUrl('<?php echo $this->getUrl('activecontent_admin/admin_slider/saveSortOrder'); ?>');
    sortorder.registerOne(<?php echo $this->getId() ?>, '<?php echo $this->getValue()?>', $('value_input_<?php echo $this->getId() ?>'), $('value_edit_<?php echo $this->getId() ?>').parentNode.parentNode, $('loader_<?php echo $this->getId() ?>'), $('btn_save_<?php echo $this->getId() ?>'));
</script>