<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Activecontent
 * @version    1.1.3
 * @copyright  Copyright (c) 2011-2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Activecontent_Block_Adminhtml_System_Config_Form_Element_Size $this */
?>

<select name="<?php echo $this->getIndex(); ?>" class="select size-field" id="<?php echo $this->getIndex(); ?>">
    <?php foreach ($this->getList() as $key => $label): ?>
    <option value="<?php echo $key; ?>" <?php if($key == $this->getValue()): ?> selected<?php endif; ?>><?php echo $label; ?></option>
    <?php endforeach; ?>
</select>

<script type="text/javascript">
//<![CDATA[

    var check_<?php echo $this->getIndex(); ?> = function(){
        if ($('<?php echo $this->getIndex(); ?>')){

            if ($('<?php echo $this->getIndex(); ?>').value == '<?php echo $this->getNoneType(); ?>'){

                if ($('<?php echo $this->getDimensionIndex(); ?>')){
                    $('<?php echo $this->getDimensionIndex(); ?>').style.display = 'none';
                }

            } else {
                if ($('<?php echo $this->getDimensionIndex(); ?>')){
                    $('<?php echo $this->getDimensionIndex(); ?>').style.display = '';
                }
            }
        }
    };

    if ($('<?php echo $this->getIndex(); ?>')){
        $('<?php echo $this->getIndex(); ?>').observe('change', function(){
            check_<?php echo $this->getIndex(); ?>();
        });
    }

    check_<?php echo $this->getIndex(); ?>();

//]]>
</script>