<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Activecontent
 * @version    1.1.3
 * @copyright  Copyright (c) 2011-2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */

/** @var Magpleasure_Activecontent_Block_Adminhtml_System_Config_Form_Element_Preview $this */
?>

<div id="mp-ac-style-preview"></div>

<script type="text/javascript">
    //<![CDATA[

    var containerClassName = 'mp-ac-style-preview';
    var imageID = 'mp_ac_style_preview_image';
    var imageClassName = 'mp-ac-style-preview-image';

    var getImageSrc = function(){

        var pattern = '<?php echo $this->getSrcPattern(); ?>';
        if ($('style')){
            return pattern.replace('{{style}}', $('style').value);
        }

        return "";
    };

    document.observe('dom:loaded', function(){

        if ($('mp-ac-style-preview')){

            $('mp-ac-style-preview').addClassName(containerClassName);

            var img = document.createElement("img");
            img.src = getImageSrc();
            img.id = imageID;
            img.className = imageClassName;
            $('mp-ac-style-preview').appendChild(img);

            if ($('style')){

                $('style').observe('change', function(){

                    $(imageID).src = getImageSrc();
                });

                $('style').observe('keyup', function(){

                    $(imageID).src = getImageSrc();
                });
            }
        }
    });


    //]]>
</script>