<?php
$helper = Mage::helper('productslider');
$sliderType = $helper->getSliderType();
$isIncludeJs = $helper->includeJs();
?>
<?php if ($helper->isActive()): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/cyberfision/productslider.css'); ?>"
          media="all"/>
    <?php if ($isIncludeJs): ?>
        <script src="<?php echo $this->getSkinUrl('js/cyberfision/productslider/jquery-1.12.3.min.js'); ?>"
                type="text/javascript"></script>
        <script src="<?php echo $this->getSkinUrl('js/cyberfision/productslider/jquery.noconflict.js'); ?>"
                type="text/javascript"></script>
    <?php endif; ?>
    <?php if ($sliderType == 'simple-slider'): ?>
        <script type="text/javascript"
                src="<?php echo $this->getSkinUrl('js/cyberfision/productslider/jquery.bxslider.min.js') ?>"></script>
        <link rel="stylesheet" type="text/css"
              href="<?php echo $this->getSkinUrl('css/cyberfision/productslider/jquery.bxslider.min.css'); ?>" media="all"/>
        <link rel="stylesheet" type="text/css"
              href="<?php echo $this->getSkinUrl('css/cyberfision/productslider/simple-slider.css'); ?>" media="all"/>
        <script type="text/javascript">
            $j = jQuery.noConflict();
            jQuery(document).ready(function () {
                $j('#list-items').bxSlider();
            });
        </script>
    <?php endif; ?>
    <?php if ($sliderType == 'slider-scrollbar'): ?>
        <script type="text/javascript"
                src="<?php echo $this->getSkinUrl('js/cyberfision/productslider/jquery-ui.min.js') ?>"></script>
        <script type="text/javascript">
            $j = jQuery.noConflict();

            jQuery(function () {
                //vars
                var conveyor = $j(".content-conveyor", $j("#sliderContent")),
                    item = $j(".item", $j("#sliderContent"));

                //set length of conveyor
                conveyor.css("width", item.length * parseInt(item.css("width")));

                //config
                var sliderOpts = {
                    max: (item.length * parseInt(item.css("width"))) - parseInt($j(".viewer", $j("#sliderContent")).css("width")),
                    slide: function (e, ui) {
                        conveyor.css("left", "-" + ui.value + "px");
                    }
                };

                //create slider
                $j("#slider").slider(sliderOpts);
            });
        </script>
        <link rel="stylesheet" type="text/css"
              href="<?php echo $this->getSkinUrl('css/cyberfision/productslider/jquery-ui.min.css'); ?>"/>
        <link rel="stylesheet" type="text/css"
              href="<?php echo $this->getSkinUrl('css/cyberfision/productslider/slidebar.css'); ?>"/>
    <?php endif; ?>
    <?php if ($sliderType == 'slider-lightbox'): ?>
        <script type="text/javascript"
                src="<?php echo $this->getSkinUrl('js/cyberfision/productslider/jquery.bxslider.min.js') ?>"></script>
        <script type="text/javascript"
                src="<?php echo $this->getSkinUrl('js/cyberfision/productslider/lightbox/jquery.fancybox.pack.js') ?>"></script>
        <script type="text/javascript">
            $j = jQuery.noConflict();

            var SKIN_URL = '<?php echo $this->getSkinUrl() ?>';

            $j(document).ready(function () {
                $j('#list-items').bxSlider({
                    minSlides: 6,
                    maxSlides: 6,
                    slideWidth: 180,
                    slideMargin: 10
                });
                $j('.lightbox').fancybox();
            });
        </script>
        <link rel="stylesheet" type="text/css"
              href="<?php echo $this->getSkinUrl('css/cyberfision/productslider/jquery.bxslider.min.css'); ?>" media="all"/>
        <link rel="stylesheet" type="text/css"
              href="<?php echo $this->getSkinUrl('css/cyberfision/productslider/jquery.fancybox.css') ?>" media="screen"/>
    <?php endif; ?>
<?php endif; ?>
