<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Activecontent
 * @version    1.1.3
 * @copyright  Copyright (c) 2011-2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<?php /** @var Magpleasure_Activecontent_Block_Adminhtml_Widget_Grid_Column_Renderer_Status_Renderer $this */ ?>

<span class="mp-ac-status">
    <?php if ($this->isEnabled()): ?>
        <?php if ($this->isVisible()): ?>
            <span class="label visible"><?php echo $this->__("Visible"); ?></span>
            <?php if ($this->willItHidden()): ?>
                <span class="label notice"><?php echo $this->__("Will be hidden %s", $this->getWillBeHiddenInDescription()); ?></span>
            <?php endif; ?>

        <?php else: ?>
            <span class="label hidden"><?php echo $this->__("Hidden"); ?></span>
            <?php if ($this->isInFuture()): ?>
                <span class="label notice"><?php echo $this->__("Will be published %s", $this->getWillBePublishedInDescription()); ?></span>
            <?php elseif ($this->isInPast()): ?>
                <span class="label notice"><?php echo $this->__("Is hidden since %s", $this->getHiddenSinceDescription()); ?></span>
            <?php endif; ?>
        <?php endif; ?>

    <?php else: ?>
        <span class="label hidden"><?php echo $this->__("Disabled"); ?></span>
    <?php endif; ?>
</span>