<?php
<!--
/**
 * Unitech Corp.
 *
 * @category   Unitech
 * @package    Unitech_LandingPage
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2015 Unitech Corp. (http://www.unitech.vn)
 */
-->
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-landing-page-importExport"><?php echo Mage::helper('unitech_landingpage')->__('Import / Export Landing Pages') ?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <?php if (!$this->getIsReadonly()): ?>
    <div class="box-left">
        <form id="import_form" action="<?php echo $this->getUrl('*/*/importPost') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('unitech_landingpage')->__('Import Landing Pages') ?></h4>
            </div>
            <fieldset>
                <legend><?php echo Mage::helper('unitech_landingpage')->__('Import Landing Pages') ?></legend>
                <input type="file" name="import_landingpage_file" class="input-file required-entry"/>
                <?php echo $this->getButtonHtml('Import Landing Pages', "this.form.submit()") ?>
            </fieldset>
        </form>
        <script type="text/javascript">
            var importForm = new varienForm('import_form');
        </script>
    </div>
    <?php endif; ?>
    <div class="<?php if ($this->getIsReadonly()): ?>box-left<?php else: ?>box-right<?php endif; ?>">
        <form id="export_form" action="<?php echo $this->getUrl('*/*/exportPost') ?>" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('unitech_landingpage')->__('Export Landing Pages') ?></h4>
            </div>
            <fieldset>
                <legend><?php echo Mage::helper('unitech_landingpage')->__('Export Landing Pages') ?></legend>
                <?php echo $this->getButtonHtml('Export Landing Pages', "this.form.submit()") ?>
            </fieldset>
        </form>
    </div>
    <div class="clear"></div>
</div>
