<?php
?><script type="text/javascript">
    var giantOSCShipmentEnterpriseGiftWrap = new MagegiantOnestepcheckoutShipmentEnterpriseGiftwrap({
        addPrintedCardCheckbox: "add-printed-card-<?php echo $this->getQuote()->getId(); ?>",
        addGiftOptionsCheckbox: "allow_gift_options",
        addPrintedCardUrl: <?php echo Zend_Json::encode($this->getAddPrintedCardAjaxUrl());?>
    });
</script>