<?php
/**
 * Created by PhpStorm.
 * Magento
 * Date: 7/21/16
 * Time: 10:12 AM
 */
?>
<input
    id="<?php echo $this->getElement()->getHtmlId() ?>"
    name="<?php echo $this->getElement()->getName() ?>"
    value="<?php echo $this->getElement()->getValue() ?>"
    title="<?php echo $this->getElement()->getTitle() ?>"
    onclick="<?php echo $this->getElement()->getData('onclick') ?>"
    onchange="updateCurrentImg(this);"
    <?php if ($this->getElement()->getData('readonly') == true): ?>readonly<?php endif ?>
    type="text"
    class="input-text"
    style="width:220px;vertical-align:top;"/>
<?php echo $this->getChildHtml('browserBtn') ?>
<?php echo $this->getChildHtml('clearBtn') ?>
<script type="text/javascript">
    window.on_<?php echo $this->getElement()->getHtmlId()?>_clear_click = function () {
        var target = $('<?php echo $this->getElement()->getHtmlId()?>');
        if (target) {
            target.value = '';
            if (fireEvent) fireEvent(target, 'change');
        }
    };
    function updateCurrentImg(element){
        var img = window.document.getElementById('preview_' + element.id);
        var holder = "<?php echo $this->getSkinUrl('ghoster/adminhtml/images/no-image.jpg'); ?>";
        if(element.value == '') {
            img.src = holder;
        } else {
            img.src = element.value;
        }
    }
</script>
