<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Ecomgems_Imagegallery
 * @version    1.0.5
 * @copyright  Copyright (c) 2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>

<?php /** @var $this Magpleasure_Imagegallery_Block_Gallery */ ?>

<?php if ($this->hasImages()): ?>
<div class="image-gallery">
    <ul class="image-gallery-content">
        <?php /** @var $image Magpleasure_Imagegallery_Model_Image */ ?>
        <?php foreach ($this->getImages() as $image): ?>
            <?php $this->getImageThumbSrc($image); ?>
            <li>
                <a class="image-gallery-thumbnail"  rel="lightbox[gallery<?php echo $this->getGallery()->getId(); ?>]" href="<?php echo $this->getImageSrc($image); ?>" title="<?php echo $this->escapeHtml($image->getLabel()); ?>">
                    <img src="<?php echo $this->getImageThumbSrc($image); ?>" alt="<?php echo $this->escapeHtml($image->getLabel()); ?>" />
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="fixed"></div>
</div>
<?php endif; ?>