<?php
/**
 * Created by PhpStorm.
 * Magento
 * Date: 7/5/16
 * Time: 6:01 PM
 */
?>
<div class="col-left sidebar sidebar-left-owl col-md-3 col-sm-12">
    <div class="sidebar-wrapper">
        <div class="block sidebar-nav-left codnitiveSidenavLeft collapse in">
            <div class="block-title">
                <strong><span><?php echo $this->__('Applications'); ?></span></strong>
            </div>
            <!-- Tab Project-->
            <div class="block-content">
                <?php if ($this->getProjects()->getSize()): ?>
                    <div id="sidebar-nav-menu" class="list_project_tab_nav nav_sidebar_left owl-carousel">
                        <?php $countSlider = 0;
                        foreach ($this->getProjects() as $project) : ?>
                            <div id="project_tab_<?php echo $project->getId(); ?>" class="item">
                                    <span class="arrow-left head-arrow-by"
                                          style="width: 8px; height: 16px; background-position: left center;"></span>
                                <?php echo $project->getData('title'); ?>
                                <?php $sbp_category_ids = Mage::helper('ghoster_shopbyproject')->getSelectedProjectCategories($project->getId()) ?>
                                <?php if (count($sbp_category_ids) > 0) : ?>
                                    <ul class="project_nav_child">
                                        <?php foreach ($sbp_category_ids as $sbp_category_id): ?>
                                            <li>
                                                <?php $sbp_category = Mage::getModel('ghoster_shopbyproject/category')->load($sbp_category_id); ?>
                                                <?php echo Mage::helper('ghoster_shopbyproject')->getCategoryName($sbp_category->getData('category_id')) ?>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                            <?php $countSlider++; endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</DIV>
<!--end left bar-->
<section class="shop_by_project app-slider-conent col-md-6 col-sm-12">
    <div class="shop_project_wrapper owl-carousel">
        <?php foreach ($this->getProjects() as $i => $project) : ?>
            <div class="item" data-project="<?php echo($project['id']); ?>">
                <?php /* @var $project GhoSter_ShopByProject_Block_Project */ ?>
                <div class="shop_project_col">
                    <?php $image_path = (Mage::helper('ghoster_common/image')->getImagePath($project->getData('project_image'))) ?>

                    <div class="shop_project_col_image">
                        <img src="<?php echo Mage::helper('ghoster_common/resizer')->init($image_path)->adaptiveResize(1130, 480); ?>">
                        <?php $sbp_category_ids = Mage::helper('ghoster_shopbyproject')->getSelectedProjectCategories($project->getId()) ?>

                        <div class="depscription">
                            <?php if($sbp_category_ids[0]): ?>
                                <?php $sbp_category = Mage::getModel('ghoster_shopbyproject/category')->load($sbp_category_ids[0]); ?>
                                <div class="depscr-application"><?php echo substr($sbp_category->getData('how_to'), 0, 210) . "..."; ?></div>
                            <?php endif ?>
                            <div class="depscr-more">
                                <a href="<?php echo Mage::getBaseUrl();?>shopbyproject/project#project_tab_<?php echo($project['id']);?>">See more</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
    <!--    <div class="see_more_project">-->
    <!--        <a href="--><?php //echo Mage::getUrl('shopbyproject/project') ?><!--"><span>-->
    <?php //echo $this->__('See More') ?><!--</span></a>-->
    <!--    </div>-->
</section>
<script>
    $j = jQuery.noConflict();
    $j(document).ready(function () {
        var syncedSecondary = true;
        var sync1 = $j('.shop_project_wrapper.owl-carousel');
        var sync2 = $j('.nav_sidebar_left.owl-carousel');
        sync1.owlCarousel({
            nav: true,
            items: 1,
            dots: true,
            loop: true,
            smartSpeed: 350,
            responsiveRefreshRate: 100
        }).on('changed.owl.carousel', syncPosition);

        sync2.on('initialized.owl.carousel', function () {
            sync2.find(".owl-item").eq(0).addClass("current");
        }).owlCarousel({
            nav: true,
            smartSpeed: 200,
            items: 5,
            dots: true,
            responsiveRefreshRate: 100
        }).on('changed.owl.carousel', syncPosition2);
        function syncPosition(el) {
            //if you set loop to false, you have to restore this next line
            //var current = el.item.index;

            //if you disable loop you have to comment this block
            var count = el.item.count - 1;
            var current = Math.round(el.item.index - (el.item.count / 2) - .5);

            if (current < 0) {
                current = count;
            }
            if (current > count) {
                current = 0;
            }

            //end block

            sync2
                .find(".owl-item")
                .removeClass("current")
                .eq(current)
                .addClass("current");
            var onscreen = sync2.find('.owl-item.active').length - 1;
            var start = sync2.find('.owl-item.active').first().index();
            var end = sync2.find('.owl-item.active').last().index();

            if (current > end) {
                sync2.data('owl.carousel').to(current, 100, true);
            }
            if (current < start) {
                sync2.data('owl.carousel').to(current - onscreen, 100, true);
            }
        }

        function syncPosition2(el) {
            if (syncedSecondary) {
                var number = el.item.index;
                sync1.data('owl.carousel').to(number, 100, true);
            }
        }

        sync2.on("click", ".owl-item", function (e) {
            e.preventDefault();
            var number = $j(this).index();
            sync1.data('owl.carousel').to(number, 300, true);
        });
    });
</script>