<?php
/**
 * Created by PhpStorm.
 * Magento
 * Date: 7/11/16
 * Time: 3:16 PM
 */

?>
<?php $categories = $this->getCategories(); ?>
<div id="project_tabs_product_content" style="">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Shop All Products')?></h4>
            <div class="form-buttons"></div>
        </div>
        <div class="fieldset " id="shop_all_product">
            <div class="hor-scroll">
                <table class="form-list" cellspacing="0">
                    <tbody>
                    <?php foreach ($categories as $category): ?>
                        <tr>
                            <td class="label">
                                <label for="products"><?php echo $category['category_name'] ?></label>
                            </td>
                            <td class="value">
                                <textarea id="products"
                                          name="products[<?php echo $category['category_id'] ?>][]"
                                          class="textarea" rows="2" cols="15"><?php echo Mage::helper('ghoster_shopbyproject')->getShopAllProducts($category['category_id'], $category['project_id']);?></textarea>
                                <p class="note" id="note_products"><span><?php echo $this->__('Enter Product SKU seperated by comma "," ex: 176456,83453,25223')?></span></p>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
