<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    0.7.8
 * @copyright  Copyright (c) 2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>



<thead ng-model="columns">
<tr class="headings">
    <th ng-repeat="column in columns" align="{{column.align}}" ng-style="{width: column.width}"
        ng-click="clickColumn(column)">
        <span class="nobr">
            <a ng-class="['','sort-arrow-asc','sort-arrow-desc'][column.sort_direction]">
                <span ng-class="['','sort-title','sort-title'][column.sort_direction]">{{column.header}}
                    <span style="float:right; font-weight: normal; font-size: xx-small;">{{column.sort_index}}
                    </span>
                </span>
            </a>
        </span>
    </th>
</tr>
<?php echo $this->getLayout()->getBlock('magpleasure.grid.filter')->toHtml(); ?>
</thead>
