<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Common
 * @version    0.7.8
 * @copyright  Copyright (c) 2014 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>

<tr ng-show="processing">
    <td class="grid-loader" colspan="{{columns.length}}">
        <?php $message_txt = $this->__("Loading..."); ?>
        <img id="grid_wait"
             src="<?php echo $this->getSkinUrl('magpleasure/images/ui-autocomplete-loader.gif') ?>"
             alt="<?php echo $message_txt; ?>"
             style="width: auto; margin-left: 40%;"
             title="<?php echo $message_txt; ?>" style="display: visible;"/>
        <?php echo $message_txt; ?>
    </td>
</tr>