<?php
/**
 * Unitech Corp.
 *
 * @category   Unitech
 * @package    Unitech_LandingPage
 * @version    0.0.1
 * @copyright  @copyright Copyright (c) 2015 Unitech Corp. (http://www.unitech.vn)
 */
?>
<?php
    $_landingPages = $this->getLandingPageCollection();
	$_helper = $this->helper('unitech_landingpage');
    $processor = Mage::helper('unitech_landingpage')->getBlockTemplateProcessor();
    $title = $_helper->getDefaultTitle() ? $_helper->getDefaultTitle() : $this->__('Bestsellers');
?>
<div class="page-title">
    <h1><?php echo $title?></h1>
</div>
<div class="std">
<?php if($_image = $_helper->getDefaultImage()): ?>
    <p><img src="<?php echo $_image ?>" alt="<?php echo $title ?>" title="<?php echo $title ?>" /></p>
<?php endif; ?>
<?php if($_description = $_helper->getDefaultMetaDescription()): ?>
    <p><?php echo $processor->filter($_description) ?></p>
<?php endif; ?>
</div>
<?php if(!$_landingPages->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no landing page(s) matching the selection.') ?></p>
<?php else: ?>
<?php
    $iterator = 1;
    $column = 1;
    $columns = $_helper->getColumnCount();
    $count = $_landingPages->count();
    $itemsPerColumn = ceil($count/$columns);
?>
<div class="landing-page page-sitemap">
    <?php echo $this->getToolbarHtml() ?>
    <div class="col<?php echo $columns ?>-set">
    <ul class="sitemap">
    <div class="col-<?php echo $column ?>">
    <?php foreach ($_landingPages as $_landingPage): ?>
        <li><a href="<?php echo $this->getItemUrl($_landingPage) ?>"><?php echo $_landingPage->getTitle() ?></a></li>
        <?php if($iterator%$itemsPerColumn==0 && $iterator < $count): ?>
            </div><div class="col-<?php echo ++$column ?>">
        <?php endif; ?>
    <?php $iterator++; endforeach; ?>
    </div>
    </ul>
    </div>
    <?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>