<?php
/**
* Unitech Corp.
*
* @category   Unitech
* @package    Unitech_LandingPage
* @version    0.0.1
* @copyright  @copyright Copyright (c) 2015 Unitech Corp. (http://www.unitech.vn)
*/
?>
<div class="modal-body">
	<form action="<?php echo $this->getSendUrl() ?>" method="post" id="product_sendtofriend_form">
		<?php echo $this->getBlockHtml('formkey')?>
		<div class="send-friend">
			<h1>Email to a Friend</h1>
			<a href="javascript:;" class="close-modal" data-dismiss="modal">X</a> 
			<div class="form">
				<div class="title">Sender:</div>
				<div class="row">
					<div class="col-md-6">
						<label><?php echo $this->__('Name:') ?><span>*</span></label>
						 <div class="input-box">
                            <input name="sender[name]" value="<?php echo $this->escapeHtml($this->getUserName()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Name')) ?>" id="sender_name" type="text" class="input-text required-entry" />
                        </div>
					</div>
					<div class="col-md-6">
						<label><?php echo $this->__('Email:') ?><span>*</span></label>
						<div class="input-box">
                           <input name="sender[email]" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" id="sender_email" type="text" class="input-text required-entry validate-email" />
                        </div>
					</div>
				</div>
				<div class="row" style="padding-top:10px;">
					<div class="col-md-12">
						<label><?php echo $this->__('Message:') ?><span>*</span></label>
						<div class="input-box">
                        <textarea name="sender[message]" class="input-text required-entry" id="sender_message" cols="3" rows="3"><?php echo $this->escapeHtml($this->getMessage())?></textarea>
                    </div>
					</div>                        
				</div>
				<div class="title">Recipient:</div>
				<div class="row">
					<ul class="form-list" id="recipients_options">
						<li class="fields">
							<div class="field col-md-6">
								<label><?php echo $this->__('Name:') ?><span>*</span></label>
								<div class="input-box">
									<input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name" />
								</div>
							</div>
							<div class="field col-md-6">
								<label><?php echo $this->__('Email Address:') ?><span>*</span></label>
								<div class="input-box">
									<input name="recipients[email][]" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" id="recipients_email" type="text" class="input-text required-entry validate-email" />
								</div>
							</div>
						</li>
					</ul>
				</div>
				
			</div>
		</div>
	</form>
	<script type="text/javascript">
    //<![CDATA[
        var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
        productSendtofriendForm.submit = function() {
            if(this.validator.validate()) {
				jQuery.ajax({
					url : sendMailURL[jQuery('#product_options').val()],
					type: "POST",
					data : jQuery("#product_sendtofriend_form").serialize(),
					beforeSend:function(){
						jQuery("#add_recipient_button,button").hide();
						jQuery(".ajax_loading").show();
					},
					complete:function(){
						jQuery("#add_recipient_button,button").show();
						jQuery(".ajax_loading").hide();
					},
					success:function(data, textStatus, jqXHR) 
					{
						data = jQuery.parseJSON(data);
						if(data){
							toastr.success("The link to a friend was sent.");
							jQuery('.mymodal').modal('hide')
						}else{
							toastr.error("There were some problems with the data."); 
						}
					},
					error: function(jqXHR, textStatus, errorThrown) 
					{
						toastr.error("There were some problems with the data.");    
					}
				});	
            }
        }.bind(productSendtofriendForm);
    //]]>
    </script>
	<script type="text/javascript">
	//<![CDATA[
		i=0;
		var recipCount  = 1;
		var maxRecip    = <?php echo $this->getMaxRecipients() ?>;
		function remove_recipient(i){
			$('recipients_name'+i).up(2).remove();
			recipCount--;
			if(recipCount<maxRecip && maxRecip != 0) {
				$('add_recipient_button').show();
				$('max_recipient_message').hide();
			}
			return false;
		}

		function add_recipient(){
			ul = $('recipients_options');
			var li_mail = Element.extend(document.createElement("LI"));
			li_mail.addClassName('fields additional-row');
			li_mail.innerHTML = '<p><a href="delete_email" title="<?php echo $this->jsQuoteEscape($this->__('Remove Email')) ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><?php echo $this->jsQuoteEscape($this->__('Remove Email')) ?>"<\/a><\/p>'
			li_mail.innerHTML += '<div class="field col-md-6"><label><?php echo $this->jsQuoteEscape($this->__('Name:')) ?><span>*</span></label><div class="input-box"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" /><\/div>';
			li_mail.innerHTML += '<div class="field col-md-6"><label><?php echo $this->jsQuoteEscape($this->__('Email Address:')) ?><span>*</span></label><div class="input-box"><input name="recipients[email][]" value="" title="<?php echo $this->jsQuoteEscape($this->__('Email Address')) ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" /><\/div><\/div>';
			i++;
			recipCount++;
			if(recipCount>=maxRecip && maxRecip != 0) {
				$('add_recipient_button').hide();
				$('max_recipient_message').show();
			}

			ul.appendChild(li_mail);
		}
	//]]>
	</script>
</div>
<div class="modal-footer">
	<img class="ajax_loading" style="display:none" src="<?php echo $this->getSkinUrl('unitech_landingpage/images/ajax.GIF')?>">
	<button type="button" onclick="productSendtofriendForm.submit()" class="button<?php if (!$this->canSend()):?> disabled<?php endif ?>"<?php if (!$this->canSend()):?> disabled="disabled"<?php endif ?>><span><span><?php echo $this->__('Send Email') ?></span></span></button>
	<div id="max_recipient_message" style="display:none;">
		<?php if ($this->getMaxRecipients()): ?>
		  <p class="limit"><?php echo $this->__('Maximum %d email addresses allowed.', $this->getMaxRecipients()) ?></p>
		<?php endif; ?>
	</div>
	<?php if (1 < $this->getMaxRecipients()): ?>
		<p id="add_recipient_button">
			<button type="button" onclick="add_recipient();" class="button"><span><span><?php echo $this->__('Add Recipient') ?></span></span></button>
		</p>
	<?php endif; ?>
</div>