<?php
?>
<?php
/**
 * Create account form template
 *
 * @var $this Mage_Customer_Block_Form_Register
 * @see app/design/frontend/enterprise/default/template/customer/form/register.phtml
 */
?>

<div class="account-create">
    <div class="title-pages">
        <div class="container">
            <h1><?php echo $this->__('Create an Wholesale Account') ?></h1>
        </div>
    </div>
    <div class="account-create-wrapper">
        <div class="container">
            <div class="account-create-content">
                <h2><?php echo $this->__('Welcome to be our member!') ?></h2>
                <p class="note-creates"><?php echo $this->__('Join us now!') ?></p>
                <?php echo $this->getChildHtml('form_fields_before') ?>
                <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                <div class="col-sm-12 margin-create-account">
                    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate"
                          enctype="multipart/form-data">
                        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>"/>
                        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>"/>
                        <input type="hidden" name="form_key"
                               value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                        <ul class="form-list">
                            <li><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?></li>
                            <li>
                                <div class="input-box">
                                    <input type="text" name="email" id="email_address"
                                           value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>"
                                           title="<?php echo $this->__('Email Address') ?>"
                                           class="input-text validate-email required-entry"
                                           placeholder="<?php echo $this->__('Email Address') ?>"/>
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="password" name="password" id="password"
                                           title="<?php echo $this->__('Password') ?>"
                                           class="input-text required-entry validate-password"
                                           placeholder="<?php echo $this->__('Password') ?>"/>
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="password" name="confirmation"
                                           title="<?php echo $this->__('Confirm Password') ?>" id="confirmation"
                                           class="input-text required-entry validate-cpassword"
                                           placeholder="<?php echo $this->__('Confirm Password') ?>"/>
                                </div>
                            </li>
                            <li>
                                <div class="input-box">
                                    <input type="text" name="postcode"
                                           value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>"
                                           title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip"
                                           class="input-text validate-zip-international required-entry validate-number"
                                           placeholder="<?php echo $this->__('Zip Code') ?>"/>
                                </div>
                            </li>

                            <li>
                                <?php echo $this->getChildHtml('customer_attributes_addon'); ?>
                            </li>

                            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                            <?php if (Mage::getStoreConfig('wholesale/general/taxvat_show') && $_taxvat->isEnabled()): ?>
                                <li>
                                    <?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?>
                                </li>
                            <?php endif ?>

                            <li>
                                <div class="input-box">
                                    <input type="text" name="company" id="company"
                                           value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>"
                                           title="<?php echo $this->__('Company') ?>" class="input-text"
                                           placeholder="<?php echo $this->__('Company') ?>"/>
                                </div>
                                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                            </li>
                            <?php if ($this->isNewsletterEnabled()): ?>
                                <li id="subscribeds">
                                    <div class="input-box">
                                        <input type="checkbox" name="is_subscribed"
                                               title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1"
                                               id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                                               class="checkbox"/>
                                    </div>
                                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                                </li>
                            <?php endif ?>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <div class="button-create-account">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="button-login-account button_registers">
                                        <a href="<?php echo Mage::getUrl('customer/account/login'); ?>"><span><?php echo $this->__('Already registered') ?></span></a>
                                    </div>
                                </div>
                                <div class="col-sm-6 btn-submit button_login">
                                    <button type="submit" class="button" title="<?php echo $this->__('Submit') ?>">
                                        <span><span><?php echo $this->__('Create an account') ?></span></span></button>
                                </div>
                            </div>
                        </div>
                    </form>
                    <script type="text/javascript">
                        //<![CDATA[
                        var dataForm = new VarienForm('form-validate', true);
                        <?php if($this->getShowAddressFields()): ?>
                        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
                        <?php endif; ?>

                        Form.getElements('form-validate').each(function (element) {
                            element.setAttribute('autocomplete', 'off');
                        });
                        //]]>
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
