<?php
$options = $this->getOptions();
$csvData = $this->getDataCsv();
?>

<table>
    <?php $i=1; foreach ($csvData as $key => $label): ?>
        <?php if (trim($label) != ''): ?>
            <tr>
                <td><b><?php echo $i ?>,</b> <?php echo $label ?></td>
                <td>
                    <select name="mapping[<?php echo $key ?>]">
                        <option value="">--Pls select one--</option>
                        <?php echo $options; ?>
                    </select>
                </td>
            </tr>
        <?php $i++; endif; ?>
    <?php endforeach; ?>
</table>
