<?php
/**
 * Created by PhpStorm.
 * Magento
 * Date: 8/12/16
 * Time: 2:37 PM
 */
?>

<?php $storeConfig = Mage::helper('wholesale')->getStoreConfig() ?>
<div class="wholesale-bar">
    <?php if (isset($storeConfig['catalog']['title'])): ?>
        <div class="bar-title"><?php echo $storeConfig['catalog']['title'] ?></div>
    <?php endif; ?>
    <div class="bar-button">
        <div class="row">
            <?php if($storeConfig['catalog']['enable_phone']):?>
                <div class="col-md-6">
                    <div class="contact-button">
                        <a href="tel:<?php echo str_replace('-','',Mage::getStoreConfig('general/store_information/phone'));?>"><?php echo $this->__('Call us at '). Mage::getStoreConfig('general/store_information/phone');?></a>
                    </div>
                </div>
            <?php endif;?>

            <?php if(isset($storeConfig['catalog']['cms_page'])):?>
                <div class="col-md-6">
                    <div class="contact-button">
                        <a href="<?php echo Mage::helper('cms/page')->getPageUrl($storeConfig['catalog']['cms_page']);?>"><?php echo $this->__('Learn more')?></a>
                    </div>
                </div>
            <?php endif;?>
        </div>
    </div>
</div>
