<?php
//$oHidePriceHelper = Mage::helper('cyberhideprice');
?>
<?php $common_products = $this->getCommonProducts(); ?>
<section class="common-product-section">
    <div class="container">
        <h3><?php echo $this->__('Upgrade Options') ?></h3>
        <div class="content-common-product">
            <div class="common-product-wrapper">
                <?php foreach ($common_products as $common_product): ?>
                    <?php /* @var $product Mage_Catalog_Model_Product */ ?>
                    <?php $product = Mage::helper('ghoster_shopbyproject/product')->getProduct($common_product->getData('product_id')) ?>
                    <div class="item">
                        <div class="col-common-product">
                            <div class="image-common-product">
                                <a href="<?php echo $product->getProductUrl();?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(300); ?>" alt="<?php echo $product->getName();?>" /></a>
                            </div>
                            <h4 class="product-name"><a href="<?php echo $product->getProductUrl();?>"><?php echo Mage::helper('ghoster_shopbyproject/product')->getCommonProductName($product)?></a></h4>
                            <?php //if ($oHidePriceHelper->isAllow() === true): ?>
                            <div class="price-common-product"><?php echo Mage::helper('core')->currency($product->getFinalPrice(), true); ?></div>
                            <?php //endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript">
    $j = jQuery.noConflict();

    $j(document).ready(function () {

        $j('.common-product-wrapper').owlCarousel({
            navigation: true,
            items : 4,
            itemsDesktop : [1199,4],
            itemsDesktopSmall : [979,3],
            itemsTablet: [768,3],
            itemsMobile : [479,1],

            navigationText: [
                "<span class='icon-arrow-left'></span>",
                "<span class='icon-arrow-right'></span>"
            ]
        });

        setHeightAuto('.common-product-wrapper', '.item .product-name');


        $j(window).resize(function () {
            setHeightAuto('.common-product-wrapper', '.item .product-name');
        });
    });
</script>
