<div class="cyberfision-socialconnect-checkout">
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if ($this->_googleEnabled() || $this->_facebookEnabled() || $this->_twitterEnabled() || $this->_linkedinEnabled() || $this->_vkEnabled()): ?>
            <div class="<?php echo $this->_getColSet(); ?> cyberfision-socialconnect-checkout">
                <h3><?php echo $this->__('Social Connect') ?></h3>

                <p><?php echo $this->__('You can continue with checkout using your <strong>Social</strong> account.') ?>

                <div class="cyberfision-socialconnect-checkout-button">
                    <?php if ($this->_googleEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_checkout_google_button') ?>
                    <?php endif; ?>

                    <?php if ($this->_facebookEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_checkout_facebook_button') ?>
                    <?php endif; ?>

                    <?php if ($this->_twitterEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_checkout_twitter_button') ?>
                    <?php endif; ?>

                    <?php if ($this->_linkedinEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_checkout_linkedin_button') ?>
                    <?php endif; ?>

                    <?php if ($this->_vkEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_checkout_vk_button') ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
