<div class="cyberfision-socialconnect-login">
    <div class="account-login">
        <div class="<?php echo $this->_getColSet(); ?> cyberfision-socialconnect-login-upper">
            <?php if ($this->_googleEnabled() || $this->_facebookEnabled() || $this->_twitterEnabled() || $this->_linkedinEnabled() || $this->_vkEnabled()): ?>
                <div class="<?php echo $this->_getColSet(); ?> new-users cyberfision-socialconnect-login-upper">
                    <div class="content">
                        <h2><?php echo $this->__('Or Social Connect'); ?></h2>

                        <p class="form-instructions"><?php echo $this->__('You can login using your Social account.'); ?></p>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="<?php echo $this->_getColSet(); ?> cyberfision-socialconnect-login-lower">
            <?php if ($this->_googleEnabled() || $this->_facebookEnabled() || $this->_twitterEnabled() || $this->_linkedinEnabled() || $this->_vkEnabled()): ?>

                <div class="cyberfision-socialconnect-login-button">

                    <?php if ($this->_googleEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_google_login_button'); ?>
                    <?php endif; ?>

                    <?php if ($this->_facebookEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_facebook_login_button'); ?>
                    <?php endif; ?>

                    <?php if ($this->_twitterEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_twitter_login_button'); ?>
                    <?php endif; ?>

                    <?php if ($this->_linkedinEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_linkedin_login_button'); ?>
                    <?php endif; ?>

                    <?php if ($this->_vkEnabled()): ?>
                        <?php echo $this->getChildHtml('cyberfision_socialconnect_vk_login_button'); ?>
                    <?php endif; ?>

                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
