<?php
/**
 * MageWorx
 * MageWorx SeoSuite Pro Extension
 *
 * @category   MageWorx
 * @package    MageWorx_SeoSuitePro
 * @copyright  Copyright (c) 2015 MageWorx (http://www.mageworx.com/)
 */
?>
<div class="switcher" style="text-align:center">
    <h4>This is SEO Suite Pro <?php echo $this->getSeoProVersion() ?>. 
        You can read <a target="_blank" style="text-decoration:none;" href="https://www.mageworx.com/index.php/downloads/dl/file/id/7/seo_suite_ultimate.pdf">FAQs</a>
        You can visit our website at <a target="_blank" style="text-decoration:none;" href="http://www.mageworx.com">mageworx.com</a>
    </h4>
</div>