<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
$imageWidth = (int)Mage::getStoreConfig('amconf/size/preview_width');
$imageHeight = (int)Mage::getStoreConfig('amconf/size/preview_height');
$smallImageSize = (int)Mage::getStoreConfig('amconf/size/thumb');
$itemCount = (int)Mage::getStoreConfig('amconf/carousel/visible_items');
?>
<?php if ((Mage::getStoreConfig('amconf/zoom/enable') || Mage::getStoreConfig('amconf/lightbox/enable'))) : ?>
    <script type="text/javascript"
            src="<?php echo Mage::getDesign()->getSkinUrl('js/amasty/amconf/zoomer.js', array()) ?>"></script>
<?php endif; ?>
<?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
<div class="amlabel-div gallery-view-image">
    <?php echo Mage::helper('amlabel')->getLabels($_product, 'product') ?>
    <?php endif; ?>
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <div class="product-image show-gallery-image">
            <?php
            $_img = '<img id="amasty_zoom" class="gallery-image"
					data-zoom-image="' . $this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight) . '" src="' . $this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight) . '"
					alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '"
				/>';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </div>

    <?php else: ?>
        <div class="product-image">
            <?php
            $_img = '<img id="amasty_zoom" class="gallery-image" data-zoom-image="' . $this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight) . '" src="' . $this->helper('catalog/image')->init($_product, 'image')->resize($imageWidth, $imageHeight) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </div>

    <?php endif; ?>
    <?php if ('true' == (string)Mage::getConfig()->getNode('modules/Amasty_Label/active')): ?>
</div>
<?php endif; ?>
<?php if (count($this->getGalleryImages()) > 0 || count(Mage::helper('ghoster_productvideo')->getVideoUrls($this->getProduct()))): ?>
    <?php $urls = Mage::helper('ghoster_productvideo')->getVideoUrls($this->getProduct());
    ?>
    <div style="position: relative;" class="more-gallery-views">
        <div id="amasty_gallery" class="product-image-thumbs">
            <?php foreach ($this->getGalleryImages() as $_image): ?>
                <a rel="group"
                   title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" <?php echo Mage::getStoreConfig('amconf/lightbox/thumbnail_lignhtbox') ? ' class="fancybox" href="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()) . '"' : ""; ?>
                   data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($imageWidth, $imageHeight); ?>"
                   data-zoom-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($imageWidth, $imageHeight); ?>">
                    <img
                            src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($smallImageSize); ?>"
                            width="<?php echo $smallImageSize; ?>" height="<?php echo $smallImageSize; ?>"
                            alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"
                            title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                </a>
            <?php endforeach; ?>

            <!-- video list -->
            <?php if (count($urls) > 0): ?>
                <?php foreach ($urls as $url): ?>
                    <a class="product-video fancybox.iframe" rel="fancyboxVideo"
                       href="<?php echo $url ?>"
                       title="<?php echo $this->escapeHtml($this->getName()) ?>"
                       data-image="<?php echo Mage::helper('ghoster_productvideo')->getVideoImage($url) ?>"
                       data-zoom-image="<?php echo Mage::helper('ghoster_productvideo')->getVideoImage($url) ?>">
                        <img
                                src="<?php echo Mage::helper('ghoster_productvideo')->getVideoThumb($url) ?>"
                                width="<?php echo $smallImageSize; ?>" height="<?php echo $smallImageSize; ?>"
                                alt="<?php echo $this->escapeHtml($this->getProduct()->getName()) ?>"
                                title="<?php echo $this->escapeHtml($this->getProduct()->getName()) ?>"
                                style="max-width: 72px"/>
                    </a>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>


        <?php if ((count($this->getGalleryImages()) + count(Mage::helper('ghoster_productvideo')->getVideoUrls($this->getProduct()))) > $itemCount && Mage::getStoreConfig('amconf/carousel/enable')): ?>
            <div id="prevGallery" style="top:<?php echo $smallImageSize / 2 - 17; ?>px"
                 class="MagicScrollArrows MagicScrollArrowPrev"></div>
            <div id="nextGallery" style="top:<?php echo $smallImageSize / 2 - 17; ?>px"
                 class="MagicScrollArrows MagicScrollArrowNext"></div>
            <?php if (Mage::getStoreConfig('amconf/carousel/pagination')): ?>
                <div id="ampagination" style="margin-top: 10px;"></div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
<script type="text/javascript">
    try {
        AmZoomerObj = new AmZoomer(<?php echo Mage::helper('amconf/zoom')->jsParam()?>);
        AmZoomerObj.loadCarousel();

        jQuery("a[rel=fancyboxVideo]").click(function () {
            jQuery.fancybox({
                'padding': 0,
                'autoScale': false,
                'transitionIn': 'none',
                'transitionOut': 'none',
                'title': this.title,
                'width': 680,
                'height': 495,
                'href': this.href.replace(new RegExp("watch\\?v=", "i"), 'v/'),
                'type': 'swf',
                'swf': {
                    'wmode': 'transparent',
                    'allowfullscreen': 'true'
                }
            });

            return false;
        });
    }
    catch (ex) {
        console.debug(ex);
    }
</script>

<script>
    jQuery(document).ready(function () {
        setTimeout(function () {
            jQuery('.product-image-thumbs').bxSlider({
                slideWidth: 75,
                minSlides: 1,
                maxSlides: 5,
                slideMargin: 10,
                pager: false,
                infiniteLoop: false
            });
        }, 2000);

        jQuery(window).resize(function () {
            var value = jQuery('.show-gallery-image').width();
            jQuery('.zoomWrapper').css({
                'height': value + 'px',
                'width': value + 'px'
            });

            jQuery('.zoomContainer').css({
                'height': value + 'px',
                'width': value + 'px'
            });
        });

    });
</script>
